<a href="https://colab.research.google.com/github/kmswin1/ConvolutionNeuralNetwork/blob/master/CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [74]:
import tensorflow as tf
import os
import cv2
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# Load the Drive helper and mount
from google.colab import drive

# This will prompt for authorization.
drive.mount('/content/drive', force_remount=True)
!ls "/content/drive/My Drive/Colab Notebooks"

Mounted at /content/drive
CNN.ipynb  data


In [80]:
RAIN_DIR = "/content/drive/My Drive/Colab Notebooks/data/Training"
train_folder_list = np.array(os.listdir(TRAIN_DIR))

train_input = []
train_label = []
label_encoder = LabelEncoder()  # LabelEncoder Class 호출
onehot_encoder = OneHotEncoder(sparse=False) # OneHotEncoder 호출
integer_encoded = label_encoder.fit_transform(train_folder_list)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)

for index in range(len(train_folder_list)):
    path = os.path.join(TRAIN_DIR, train_folder_list[index])
    path = path + '/'
    img_list = os.listdir(path)
    for img in img_list:
        img_path = os.path.join(path, img)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        train_input.append([np.array(img)])
        train_label.append([np.array(onehot_encoded[index])])
        print (np.array(img))

print (train_input)
train_input = np.reshape(train_input, (-1, 50400))
train_label = np.reshape(train_label, (-1, 2))
train_input = np.array(train_input).astype(np.float32)
train_label = np.array(train_label).astype(np.float32)
np.save("train_data.npy", train_input)
np.save("train_label.npy", train_label)


[[ 21  21  21 ...  10  10  10]
 [ 21  21  20 ...  10  10  10]
 [ 21  20  20 ...  11  10  10]
 ...
 [120  91 115 ...  26  46 101]
 [ 99 107  78 ...  26  47  96]
 [ 71  92 100 ...  28  45  92]]
[[ 24  30  28 ...  30  27  29]
 [ 27 248 255 ... 255 253  30]
 [ 20 255  24 ...  15 255  29]
 ...
 [ 23 252  25 ...  24 253  38]
 [ 25 254 255 ... 255 254  38]
 [ 26  23  28 ...  21  26  27]]
[[215 163 168 ... 155 155 156]
 [203 157 163 ... 155 156 156]
 [196 161 166 ... 156 156 156]
 ...
 [ 71 147 171 ... 141 126 112]
 [139 169 168 ... 151 150 149]
 [185 166 166 ... 160 149 140]]
[[132 132 132 ... 191 191 191]
 [133 133 133 ... 191 191 191]
 [133 133 133 ... 191 191 191]
 ...
 [140 140 142 ...  62  66  70]
 [171 180 195 ...  36  38  40]
 [234 232 228 ...  45  43  41]]
[[array([[ 21,  21,  21, ...,  10,  10,  10],
       [ 21,  21,  20, ...,  10,  10,  10],
       [ 21,  20,  20, ...,  11,  10,  10],
       ...,
       [120,  91, 115, ...,  26,  46, 101],
       [ 99, 107,  78, ...,  26,  47,  96]

ValueError: ignored